In [91]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [92]:

iris = pd.read_csv('Iris.csv',encoding='utf-8') # read iris data for predict to label
labels = iris['Species'] # real label of iris data set
size = len(iris) # the number of iris data set
roundN = 10 # the number of bagging round

# read iris bagging dataset (1)~(10) for round 10 
samples = []
sample = pd.read_csv('Iris_bagging_dataset (1).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (2).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (3).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (4).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (5).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (6).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (7).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (8).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (9).csv',encoding='utf-8')
samples.append(sample)
sample = pd.read_csv('Iris_bagging_dataset (10).csv',encoding='utf-8')
samples.append(sample)

In [93]:
tree_predicts = [] # results of predict in each bagging round about iris data(150)

# bagging 10 round
for i in range(roundN) :
    tree_clf = DecisionTreeClassifier(criterion='entropy',random_state=0) # Define Decision Tree Classifier
    X = samples[i].iloc[:,1:5] # exclude attribute 'id' and 'Species'
    y = samples[i]['Species'] # labels about bagging data set
    tree_clf.fit(X,y) # training by using bagging data set(10) which has each 150 data
    tree_predicts.append(tree_clf.predict(iris.iloc[:,1:5])) # append results of predict in each bagging round
    
tree_predicts = np.array(tree_predicts) # type conversion for majority voting

In [94]:
total_predict = [] # total results of predicted label(150) by majority voting 

# Majority bagging
for i in range(size) :
    # aggregation 10 classifier get from each bagging round and calculate the number of element to each label
    result = Counter(tree_predicts[:,i])
    
    total_predict.append(result.most_common(1)[0][0]) # get the most common predicted label about 150 data

In [104]:

print(classification_report(labels,total_predict,
                            target_names=['Iris-setosa', 
                                          'Iris-versicolor', 'Iris-virginica']))

# make confusion matrix about real labels and predicted labels by using 'confusion_matrix'
confusion = confusion_matrix(labels,total_predict,labels=['Iris-setosa', 
                                          'Iris-versicolor', 'Iris-virginica'])

print("Order: setosa, versicolor, virginica")
print(confusion)

# accuracy = (TP+TN)/N 
accuracy = ( confusion[0][0] + confusion[1][1] + confusion[2][2] ) / size
print("Accuracy: ",accuracy)

print("\n\n ** Predict result **")
total_predict = pd.DataFrame(total_predict)
print(total_predict)





                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        50
Iris-versicolor       0.96      0.96      0.96        50
 Iris-virginica       0.96      0.96      0.96        50

    avg / total       0.97      0.97      0.97       150

Order: setosa, versicolor, virginica
[[50  0  0]
 [ 0 48  2]
 [ 0  2 48]]
Accuracy:  0.9733333333333334


 ** Predict result **
                  0
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
5       Iris-setosa
6       Iris-setosa
7       Iris-setosa
8       Iris-setosa
9       Iris-setosa
10      Iris-setosa
11      Iris-setosa
12      Iris-setosa
13      Iris-setosa
14      Iris-setosa
15      Iris-setosa
16      Iris-setosa
17      Iris-setosa
18      Iris-setosa
19      Iris-setosa
20      Iris-setosa
21      Iris-setosa
22      Iris-setosa
23      Iris-setosa
24      Iris-setosa
25      Iris-setosa
26      Iris-setosa
27      Iris-setosa
28  